import type { Categoria } from "@/lib/models/category";

/**
 * Cardápio completo da Anne, organizado por categoria — carga inicial do catálogo.
 */
export const SEED_DISHES_BY_CATEGORY: Record<Categoria, string[]> = {
  "Petit Gourmet Volante": [
    "Tartar de salmão com guacamole",
    "Ceviche de polvo ao vinagrete trufado com musseline de mandioquinha",
    "Panelinha com creme de brie e geleia de damasco",
    "Camarão ao champagne",
    "Salmão ao champagne",
    "Bacalhau brulle",
    "Filezinho ao capuccino",
  ],
  "Canapés Frios": [
    "Sable folhado com camarão e musse de mandioquinha trufada",
    "Steak tartar, aioli e crosta de grana padano",
    "Macarron com mousse de blue cheese e nozes",
    "Mousse de chevre e tuile de castanhas",
    "Tartar de salmão com tuile de gergilim",
    "Rosbife com creme camembert, alho negro e crosta de grano padano",
    "Amuse lagosta com laranja",
    "Cestinha de truta com ovas de salmão",
    "Casquinha de brandade de bacalhau com crocante de parma",
    "Esfera de queijo de cabra na torradinha artesanal",
    "Beiju com purê de banana da terra e carne seca",
    "Beiju de tapioca com ceviche",
    "Bigne com creme de queijos e farofa de pistache",
    "Bigne de parmesão com borsin e tapenade",
    "Blinis com sour cream e camarão",
    "Blinis com sour cream e salmão defumado",
    "Bombom de burrata com tomatinho confit e pesto de manjericão",
    "Canapé folhado com musse de queijo de chevre e frutas vermelhas",
    "Cannoli de crudo de salmão, emulsão de avocado e ovas negras",
    "Canoa de vinagrete de polvo ao aroma de azeite trufado",
    "Carpaccio no pão preto, com alcaparras",
    "Cestinha com musse de baroa e camarão",
    "Ceviche de banana da terra na gamelita",
    "Crostillant com carpaccio e alcaparras",
    "Crostillant com steak tartare de filet",
    "Macarrons com gorgonzola e nozes",
    "Macarons com chevre e frutas vermelhas",
    "Mini taco com guacamole",
    "Philo com foie gras e geleia de cebola caramelada",
    "Presunto de Parma com queijo brie, figo fresco com mel",
    "Presunto parma com palmito e manjericão",
    "Profiteroles de bacalhau",
    "Profiteroles de haddock",
    "Sable folhado com camarão",
    "Sable folhado com musse de baroa e camarão",
    "Steak tartare com torradinha",
    "Stick de banana da terra com brie e parma",
    "Stick de frango ao curry com gergelim e geleia de damasco",
    "Stick de mini caprese ao molho pesto",
    "Stick de mozzarella de búfala e salame milano com molho teriyaki",
    "Stick de parma com melão orange",
    "Tule de gergilim com tartar de atum",
    "Tule de gergilim com creme de haddock ao limone",
  ],
  "Canapés Quentes": [
    "Bao de porco glaceado com picles de cebola roxa",
    "Bruscheta de mix de cogumelos",
    "Bruscheta de parma",
    "Bruschetta caprese",
    "Brusqueta de queijo de cabra, damasco e mel au gratin",
    "Camarão crocante ao limone",
    "Camarão empanado com coco ao molho de maracujá",
    "Cestinha de bacalhau brulle",
    "Tortinha philo com mix de cogumelos",
    "Tortinha philo com ragu de cordeiro",
    "Tortinha philo com ragu de pato",
    "Cestinha philo de queijo brie com geleia de damasco",
    "Cone com creme de salmão marinado",
    "Croqueta de cordeiro com dip de hortelã",
    "Croqueta de cupim com dip de gengibre",
    "Croqueta de pato ao molho de laranja",
    "Mini taco com chilli beef",
    "Stick de filé com noisete e geleia de alho negro",
    "Stick de frango ao molho de queijos",
    "Stick de mignon com geleia de alho negro",
    "Cestinha philo de brie ao mel trufado",
    "Trouxinha de pato com laranja",
    "Mini pastel de queijo canastra com melado",
    "Bolinho de bacalhau com azeite",
    "Cheeseburger (junk food na pista)",
    "Batata frita (junk food na pista)",
  ],
  "Forno e Fogão": [
    "Batatinha com bacalhau",
    "Batatinha recheada alho poró e nirá",
    "Batatinha recheada com carne seca",
    "Batatinha recheada quatro queijos",
    "Batatinha recheada salmão e alcaparras",
    "Bolinha de bobó de camarão com geleia de pimenta",
    "Bolinha de provolone com alho poró e melado",
    "Bolinha de queijo com geleia de pimenta",
    "Bolinho de feijoada ao molho de manjericão",
    "Coxinha de costela com molho barbecue",
    "Coxinha gourmet com molho de queijos",
    "Crocante de queijo com melado",
    "Croquete alemão com mostarda escura",
    "Croqueta de ragu",
    "Dadinho de tapioca com melado de cana",
    "Tartalete cremosa de bobó de camarão",
    "Cestinha de brie com damasco",
    "Harumaki de bacalhau com molho de limão siciliano",
    "Harumaki de camarão com geleia de pimenta à parte",
    "Harumaki de filé suíno ao molho de abacaxi e mostarda",
    "Harumaki de pato com chutney de laranja",
    "Harumaki de salmão com kani ao agridoce",
    "Kafta com molho de hortelã",
    "Mini filé wellington com dip de mostarda e mel",
    "Mini pastel com ragu de carne",
    "Mini pastel de camarão",
    "Mini pastel de queijo da canastra",
    "Mini quibe com molho de iogurte",
    "Mini quiche blue cheese e maçã",
    "Mini quiche de alho poró",
    "Mini quiche de brie com geleia de damasco",
    "Mini quiche de chèvre e cebola caramelizada",
    "Mini quiche lorraine",
    "Vol-au-vent cremoso de salmão",
    "Vol-au-vent de brie com damasco",
    "Vol-au-vent de cogumelos",
  ],
  "Mini Jantar Volante": [
    "Arroz de camarão à moda Thai",
    "Arroz de pato com shitake, molho de vinho merlot",
    "Batata rústica com iscas de filet ao molho ferrugem",
    "Bobó de camarão com arroz de coco e farofinha",
    "Bobó de shitake",
    "Escondidinho de bacalhau",
    "Escondidinho de filet com queijos",
    "Escondidinho de camarão ao champagne",
    "Escondidinho de carne seca flambada com queijos cremosos",
    "Escalopinho com arroz à piemontese",
    "Escalopinho ao molho de gorgonzola com arroz de amêndoas",
    "Brandada de bacalhau com alho-poró e parmesão",
    "Bacalhau com batata palha e arroz com brócolis",
    "Linguado beurre blanc de coco com musseline de baroa",
    "Peixe branco ao molho de limão com batata aligot",
    "Picadinho de mignon com arroz de castanha e batatinha palha",
    "Filezinho de mignon ao molho madeira com musseline de mandioquinha",
    "Filé mignon ao molho de vinho do porto com musseline de mandioquinha",
    "Filé mignon com crosta de parmesão ao molho escuro com risoto de alho poró",
    "Filé mignon com crosta de brie ao molho de ervas com risoto de funghi",
    "Ragu de costela ao barbecue sobre polentinha cremosa",
    "Nhoque de baroa com molho de gorgonzola e nozes",
    "Nhoque de bacalhau com fonduta de queijos",
    "Ravioli de queijos com molho de costela desfiada ao vinho",
    "Ravioli de brie com molho de cogumelos",
    "Ravioli recheado de mix de cogumelos ao molho de queijo azul",
    "Risoto ao quatro queijos com filet ao molho de cogumelos",
    "Risoto de bacalhau com crisp de parma",
    "Risoto de bisque de camarão e camarões flambados",
    "Risoto ao limone com filet de salmão",
    "Risoto de grana padano com medalhão ao bernaise",
    "Risoto trio de cogumelos e pangratato de ervas",
    "Risoto com queijo azul, pistache e pêra ao vinho",
    "Risoto al mare",
    "Nhoque de baroa com molho de cogumelos",
    "Ragu de cordeiro com aligot de batatas",
  ],
  "Mini Jantar Estacionado": [
    "Salada bouquet de folhas verdes com lascas de parmesão, fatias de parma e redução de balsâmico",
    "Medalhões de salmão ao molho champagne",
    "Robalo com crosta de ervas ao beurre blanc",
    "Escalope mignon ao molho madeira, vinho, cogumelos ou crosta de ervas ao demi glace",
    "Bobó de camarão",
    "Risoto de arroz negro ao limone",
    "Risoto de parmesão reggiano",
    "Risoto de cogumelos ao funghi",
    "Musseline de batatas trufadas",
    "Legumes baby glaceados",
    "Musseline de batata baroa",
    "Aligot",
    "Arroz de coco com farofa de dendê",
    "Raviole artesanal de cogumelos com manteiga de sálvia e nozes carameladas",
  ],
  "Ilha Estacionada / Antepasto": [
    "Pizza branca (item fixo)",
    "Seleção de pães, torradas e chips artesanais (item fixo)",
    "Gateau de roast beef (item fixo)",
    "Gateau de camarão (item fixo)",
    "Terrine de salmão (item fixo)",
    "Salada caprese (item fixo)",
    "Pirâmide de foie gras com geleia de amora (item fixo)",
    "Couscous al mare (item fixo)",
    "Queijo parmesão em peça (item fixo)",
    "Queijo gorgonzola em peça (item fixo)",
    "Salame Milani e presunto parma (item fixo)",
    "Trio de Homus",
    "Mix de cogumelos flambados",
    "Carpaccio de carne com pesto e alcaparras",
    "Carpaccio de salmão defumado ao tartufo de ervas e sour cream",
    "Burrata com tapenade de azeitona e pesto de manjericão",
    "Torre de figo no mel, parma e gorgonzola",
    "Ceviche de peixe branco",
    "Salmão Gravlax com creme azedo",
    "Brie folhado com torre de favo de mel",
    "Steak tartare com tuile de parmesão",
  ],
  "Sobremesas": [
    "Mini banoffee",
    "Brownie de chocolate com fondue de chocolate intenso",
    "Mousse de chocolate meio amargo",
    "Cocada cremosa com toque de leite condensado",
    "Churros com doce de leite argentino",
  ],
  "Estações Extras": [
    "Peça de presunto de Parma (acompanha melão, figos, redução de balsâmico e rúcula) — R$ 30 por convidado",
    "Ilha de massa italiana ou risoteria, diversos molhos e finalizações — R$ 28 por convidado",
    "Bar de ceviche: peixes, polvo, camarões, banana da terra, manga, kiwi, limão, manjericão, cebola roxa, coentro — R$ 32 por convidado",
    "Ilha de fondue de chocolate nobre com frutas da estação, marshmallows e acompanhamentos — R$ 28 por convidado",
    "Ilha de sobremesas (6 a 8 opções), mini sobremesas variadas e sofisticadas — R$ 32 por convidado",
  ],
};
