services:

  db:
    image: postgres:17-alpine
    container_name: ficha-tecnica-anne
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: klohjoao/ficha-backend:latest
    container_name: ficha-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: ficha-buffet
      DB_NAME: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      URL_FRONTEND: ${URL_FRONTEND}
      COOKIE_SECURE: ${COOKIE_SECURE}
      URL_DB: ${URL_DB}
      RSA_PUBLIC_KEY_PATH: /run/secrets/public_key
      RSA_PRIVATE_KEY_PATH: /run/secrets/private_key
    volumes:
      - /caminho_private_key_local:/caminho_private_key_container
      - /caminho_public_key_local:/caminho_public_key_container
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    image: klohjoao/ficha-frontend:latest
    container_name: ficha-frontend
    restart: unless-stopped
    environment:
      API_BASE_URL: http://backend:8080
      NODE_ENV: production
      BLOB_READ_WRITE_TOKEN: ${BLOB_READ_WRITE_TOKEN}
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  postgres_data: